### ISSUE TITLE
Errors when launching crucible app and trying to add first server for testing

### ISSUE THREAD

**Issue by mecklaiz** [fhir-crucible/crucible#105]
I am trying to set up the crucible app in order to test a FHIR server implementation for conformance. However, on Windows and CentOS after starting the app and putting in a URL the server logs the following error message from the URL (as found in the logs)

http://localhost:3000/servers/568ed8fde13823084c000001/aggregate_run?only_failures=true

```
Missing template servers/aggregate_run, application/aggregate_run with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in: * "/home/zmecklai/apps/crucible/crucible/app/views" * "/home/zmecklai/.rvm/gems/ruby-2.3.0/gems/magic_lamp-1.5.2/app/views" * "/home/zmecklai/.rvm/gems/ruby-2.3.0/gems/teaspoon-1.1.1/app/views" * "/home/zmecklai/.rvm/gems/ruby-2.3.0/gems/devise-3.4.0/app/views"
```

The app was launched like this: 
    bundle exec rails server -b0.0.0.0

Here's another statement of the same issue as reported by the app

```
Mongoid::Errors::DocumentNotFound in ServersController#aggregate_run
Problem: Document(s) not found for class Server with id(s) 568ed8fde13823084c000001. Summary: When calling Server.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 568ed8fde13823084c000001 ... (1 total) and the following ids were not found: 568ed8fde13823084c000001. Resolution: Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.

Extracted source (around line #106):
104
105  def aggregate_run
106      server = Server.find(params[:server_id])
107    aggregate_run = server.aggregate_run      
108    return unless aggregate_run
109    if (params[:only_failures])

Rails.root: /home/zmecklai/apps/crucible/crucible

Application Trace | Framework Trace | Full Trace
app/controllers/servers_controller.rb:106:in `aggregate_run'
Request

Parameters:

{"only_failures"=>"true",
"format"=>:json,
"server_id"=>"568ed8fde13823084c000001"}
```

**Comment by andrequina** [comment]
Is this error making it to the UI or is this just in the logs?  The aggregate run request is a AJAX JSON request so if it fails the result should just be that you are missing the third tab on the server page... the tabs being (tests, conformance, test run summary). The test run summary tab would not be displayed.

While I have not been able to reproduce the issue, perhaps you are seeing it because you have not run any tests for the server in question?  It is odd that the error is "missing template" since the aggregate_run method on the servers controller renders json directly... therefore a template should not be required at all.

We recently added CentOS installation instructions:
https://github.com/fhir-crucible/crucible/wiki/Installation-Instructions-(CentOS-7.1.1503)

Did you use those instructions or did you install on your own?

Can you check what version of ruby and rails you're on?

bundle exec rails -v
ruby -v

Are you up-to-date on master?

**Comment by mecklaiz** [comment]
I'm sorry, it appears that this error is a red herring. I will close this issue and open a new issue with a more accurate report of the problem which is basically that after the app comes up and I provide a server to test it shows the progress indicator and then spins "forever" without showing any results. I will open a new issue for that.
