### ISSUE TITLE
Escaping Plus Sign in Query Strings

### ISSUE THREAD

**Issue by jawalonoski** [fhir-crucible/crucible#220]
Submitted via email:

> Hi,
> My server is failing test “AS4006_dateWritten: Search for MedicationOrder by dateWritten”:
>      
>     `GET https://.../fhir/MedicationOrder?datewritten=2013-05-25T19:32:52+01:00`
>  
> The underlying technology my server is built on automatically escapes the “+” in the query to a space, which makes the value not a valid date parameter:
>     2013-05-25T19:32:52 01:00
>  
> Which is causing my server to error.
>  
> I couldn’t find anything really definitive that says a plus sign in a URL is not valid, but I found many things that say that a literal “+” in a query string is shorthand for a space character, and an actual plus sign in a query value should be URL escaped: “%2B”.  The most definitive thing I found is this “recommendation” from w3.org:
>     https://www.w3.org/Addressing/URL/4_URI_Recommentations.html
>  
> Section “Query strings”.
>  
> Can the test be changed to URL escape the plus sign?
>

**Comment by jorge-delagarza** [comment]
My server is also having trouble with "SE01P: Search patients without criteria (except _count)" because of this:
    POST https://argonaut.intersystems.com/fhir/Patient/_search?_count=1&_format=application/xml+fhir

It escapes the plus sign to a space and then errors because that makes the _format value not valid.

**Comment by jorge-delagarza** [comment]
Same thing with suit "Format Test" in group "Core Functionality".  All of the tests on the "_format" parameter have unescaped plus signs in the query strings.

**Comment by arscan** [comment]
This is an interesting one.  It works as you would expect when plan_executor (our test engine) was run as a standalone application, but wasn't when called from Crucible.  Turns out Crucible has a dependency that overwrote another dependency that plan_executor was using with an old version.  That old version didn't replace '+' with %2B as one would expect.  This is being addressed in #230 and #231, and will probably get deployed next week.  Thanks again for the report!

**Comment by arscan** [comment]
This has been deployed.  Closing now but let us know if you are still having problems with this.  Thanks!
