### ISSUE TITLE
"Transaction and Batch Test" tests all getting "undefined method `each' for nil:NilClass "

### ISSUE THREAD

**Issue by jorge-delagarza** [fhir-crucible/crucible#222]
My server is failing all of the tests in the "Transaction and Batch Test" suite under Core Functionality and I'm not sure why. It could be a problem with Crucible.

For example for test "XFER0: Create a Patient Record as Transaction" Crucible posts a Bundle with type.value="transaction" (attached) to my endpoint.  After creating each resource my server responds with a Bundle with type.value="transaction-response" (also attached).  However Crucible seems to be getting an error trying to parse the response.  Rather than giving a reason for the test failing, the message is just: "undefined method `each' for nil:NilClass".  The same goes for every other test in that suite.

If this is a problem with my server's response, the message should be fixed to be more helpful in conveying the reason for failure.  Otherwise the error should be fixed.

Also, it seems that when Crucible gets an error parsing a response, we lose the ability to inspect the request and response in the Crucible UI.  Ideally this would be fixed.

[transaction-request.txt](https://github.com/fhir-crucible/crucible/files/732665/transaction-request.txt)
[transaction-response.txt](https://github.com/fhir-crucible/crucible/files/732667/transaction-response.txt)

**Comment by arscan** [comment]
Sorry for the slow response here @jorge-delagarza -- we really appreciate your bug reports but it might take us a little while to resolve them all.

For this issue, it appears that we were skipping a test that initiated a variable we needed, so I moved it to the setup here: https://github.com/fhir-crucible/plan_executor/commit/6d2a2de03a4a9302693a44b0e387d7ef8214544c

I reran it on your server and now it isn't giving Crucible (purple triangle) errors anymore, so you can inspect the output.  In order to test it, I had to clear out your credentials again -- I hope that is ok.

**Comment by jorge-delagarza** [comment]
I can see now we're getting good pass/fails on all the tests in this suite.  Thanks Rob.

**Comment by arscan** [comment]
Sounds good.  I'll close this and if you find other problems on our side with this test suite just go ahead and open a new issue.  Thanks again.
