### ISSUE TITLE
Problem during setup of "Sprinkler Search Test" suite

### ISSUE THREAD

**Issue by jorge-delagarza** [fhir-crucible/crucible#224]
In the "Sprinkler Search Test" suite, Crucible does a parameter-less Patient search as a setup step.  Then, whatever was the first resource returned by that search, Crucible creates a Condition that references that patient.  Only the actual reference is kind of messed up.  For example:
```
<patient id="701">
    <reference value="/Patient/701?_format=application/xml+fhir"/>
    <display value="dXmhj6xWW3qSW6N6yTvg6g=="/>
</patient>
```

I'm not *certain* that the reference value is invalid, but at the very least, it's unusual, for two reasons.  Obviously the query parameter, but also because of the leading slash.  Every other example I've seen of a relative URL in a reference value has been formatted as "[type]/[id]".  The way this reference value is formatted is causing my server to fail several subsequent tests in this suite.  For example "SE05.0P: Search condition by patient reference url (partial)":
     POST https://argonaut.intersystems.com/fhir/Condition/_search?_format=application/xml+fhir&patient=Patient/701

Can the reference value be simplified to (for example) "Patient/701"?

**Comment by arscan** [comment]
I looked around in the spec and couldn't find any definitive answer to whether or not the leading slash is valid.  One the one hand, since it isn't specific in the specification, then perhaps your server should support both.  But on the other hand, all the examples omit the leading slash as you pointed out, making that the de-facto right solution.

In the end, I removed the slash, because in other tests we explicitly removed the slash (even though our client wants to put it in there).  So I figured we might as well be consistent.

I also got rid of the format portion, that doesn't make sense and we remove it in other tests.

Changes are in https://github.com/fhir-crucible/plan_executor/commit/9d4a1fcf0b498fc635ec147322a07ddab97b827a

I deployed it, so you should see the new behavior on the server.

**Comment by arscan** [comment]
This should be all set.  Please let me know if this problem hasn't been fixed from your perspective.  Thanks!
